CREATE TABLE [dbo].[ROLE_DETAIL]
(
	[USER_ID] INT NOT NULL,
	[ROLE_ID] INT NOT NULL,
	[ACTIVE] BIT NOT NULL DEFAULT 1,
	CONSTRAINT [PK_ROLE_DETAIL] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [ROLE_ID]  ASC)
)
