CREATE TABLE [dbo].[ROLE]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(50) NOT NULL,
	[DESCRIPTION] VARCHAR(250) NULL,
	[ROLE_GROUP_ID] INT NOT NULL,
	CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED ([ID] ASC)
)
