CREATE TABLE [dbo].[USER] (
    [ID]            INT NOT NULL IDENTITY,
    [USERNAME]      VARCHAR (50) NOT NULL,
    [PASSWORD]      VARCHAR (32) NOT NULL,
	[ACTIVE]        BIT NOT NULL DEFAULT '1',
	[USER_TYPE_ID]  TINYINT,
	[EXTERNAL_USER_ID] INT,
    CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([ID] ASC)
);

