CREATE TABLE [dbo].[INVENTORY_TRANSACTION]
(
	[ID]				INT NOT NULL IDENTITY(1,1),
	[TYPE_ID]			TINYINT,
	[PRODUCT_ID]		INT,
	[QUANTITY]			INT NOT NULL,
	[PURCHASE_ORDER_ID]	INT,
	[CUSTOMER_ORDER_ID]	INT,
	[COMMENTS]			VARCHAR(250),
	[TRANSACTION_CREATED_DATE] DATETIME NULL, 
    [TRANSACTION_MODIFIED_DATE] DATETIME NULL, 
    CONSTRAINT [PK_INVENTORY_TRANSACTION] PRIMARY KEY CLUSTERED ([ID] ASC)
)
