CREATE TABLE [dbo].[INVENTORY_TRANSACTION]
(
	[ID]				INT NOT NULL IDENTITY,
	[TYPE_ID]			TINYINT,
	[PRODUCT_ID]		INT,
	[QUANTITY]			INT NOT NULL,
	[PURCHASE_ORDER_ID]	INT,
	[CUSTOMER_ORDER_ID]	INT,
	[COMMENTS]			VARCHAR(250),
	CONSTRAINT [PK_INVENTORY_TRANSACTION] PRIMARY KEY CLUSTERED ([ID] ASC)
)
