CREATE TABLE [dbo].[INVOICE]
(
	[ID]            INT NOT NULL IDENTITY,
	[ORDER_ID]      INT,
	[INVOICE_DATE]  DATETIME,
	[DUE_DATE]      DATETIME,
	[TAX]           DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[SHIPPING]      DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[AMOUNT_DUE]    DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	CONSTRAINT [PK_INVOICES] PRIMARY KEY CLUSTERED ([ID] ASC)
)
