CREATE TABLE [dbo].[ORDER]
(
	[ID]              INT NOT NULL IDENTITY,
	[EMPLOYEE_ID]     INT,
	[CUSTOMER_ID]     INT,
	[ORDER_DATE]      DATETIME,
	[SHIPPED_DATE]    DATETIME,
	[SHIPPER_ID]      INT,
	[SHIP_NAME]       VARCHAR(50),
	[SHIP_ADDRESS]    VARCHAR(250),
	[SHIP_CITY]       VARCHAR(50),
	[SHIP_STATE_PROVINCE]  VARCHAR(50),
	[SHIP_ZIP_POSTAL_CODE]	VARCHAR(50),
	[SHIP_COUNTRY_REGION]	VARCHAR(50),
	[SHIPPING_FEE]			DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[TAX]					DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[TAX_RATE]				DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[PAYMENT_TYPE]			VARCHAR(50),
	[PAID_DATE]				DATETIME,
	[NOTES]					VARCHAR(250),
	[TAX_STATUS_ID]	TINYINT,
	[STATUS_ID]       TINYINT,
	CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED ([ID] ASC)
)
