CREATE TABLE [dbo].[ORDER_DETAIL]
(
	ID                  INT NOT NULL IDENTITY,
	ORDER_ID            INT NOT NULL,
	PRODUCT_ID          INT,
	QUANTITY            DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	UNIT_PRICE          DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	DISCOUNT            DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	DATE_ALLOCATED      DATETIME,
	STATUS_ID           TINYINT,
	PURCHASE_ORDER_ID   INT,
	INVENTORY_ID        INT,
	CONSTRAINT [PK_ORDER_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
)
