CREATE TABLE [dbo].[PRODUCT]
(
	[ID]						INT NOT NULL IDENTITY(1,1),
	[CODE]						VARCHAR(25),
	[NAME]						VARCHAR(50),
	[DESCRIPTION]				VARCHAR(250),
	[STANDARD_COST]				DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[PRICE]						DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[REORDER_LEVEL]				INT,
	[TARGET_LEVEL]				INT,
	[QUANTITY_PER_UNIT]			INT,
	[MINIMUM_REORDER_QUANTITY]	INT,
	[DISCONTINUED]				BIT NOT NULL DEFAULT '0',
	[SUB_CATEGORY_ID]			INT,
	[ATTACHMENTS]				VARBINARY(MAX),
	CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED ([ID] ASC)
)
