CREATE TABLE [dbo].[PURCHASE_ORDER]
(
	[ID]              INT NOT NULL IDENTITY,
	[SUPPLIER_ID]     INT,
	[CREATED_BY]      INT,
	[CREATION_DATE]   DATETIME,
	[SUBMITTED_BY]    INT,
	[SUBMITTED_DATE]  DATETIME,
	[APPROVED_BY]     INT,
	[APPROVED_DATE]   DATETIME,
	[STATUS_ID]       TINYINT,
	[EXPECTED_DATE]   DATETIME,
	[SHIPPING_FEE]    DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[TAX]			  DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[PAYMENT_AMOUNT]  DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[PAYMENT_DATE]    DATETIME ,
	[PAYMENT_METHOD]  VARCHAR(50) ,
	[NOTES]           VARCHAR(250) ,
	CONSTRAINT [PK_PURCHASE_ORDER] PRIMARY KEY CLUSTERED ([ID] ASC)
)
