CREATE TABLE [dbo].[PURCHASE_ORDER_DETAIL]
(
	[ID]                  INT NOT NULL IDENTITY(1,1),
	[PURCHASE_ORDER_ID]   INT,
	[PRODUCT_ID]          INT,
	[INVENTORY_ID]        INT,
	[QUANTITY]            DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[UNIT_COST]           DECIMAL(19,4) NOT NULL DEFAULT '0.0000',
	[DATE_RECEIVED]       DATETIME,
	[POSTED_TO_INVENTORY] BIT NOT NULL DEFAULT '0',
	CONSTRAINT [PK_PURCHASE_ORDER_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
)
