CREATE VIEW [dbo].[CUSTOMER_ORDERS]
	AS SELECT
dbo.[CUSTOMER].ID AS [CUSTOMER_ID],
dbo.[CUSTOMER].LAST_NAME + ', ' + dbo.[CUSTOMER].FIRST_NAME AS [CUSTOMER_NAME],
dbo.[ORDER].ID AS [ORDER_ID],
dbo.[EMPLOYEE].LAST_NAME + ', ' + dbo.[EMPLOYEE].FIRST_NAME AS [EMPLOYEE_NAME],
SUM(dbo.[ORDER_DETAIL].UNIT_PRICE) AS [TOTAL]
FROM
dbo.[CUSTOMER]
INNER JOIN dbo.[ORDER] ON dbo.[ORDER].CUSTOMER_ID = dbo.[CUSTOMER].ID
INNER JOIN dbo.[ORDER_DETAIL] ON dbo.[ORDER_DETAIL].ORDER_ID = dbo.[ORDER].ID
INNER JOIN dbo.[EMPLOYEE] ON dbo.[ORDER].EMPLOYEE_ID = dbo.[EMPLOYEE].ID
GROUP BY
dbo.[CUSTOMER].ID,
dbo.[ORDER].ID,
dbo.[CUSTOMER].FIRST_NAME,
dbo.[CUSTOMER].LAST_NAME,
dbo.[EMPLOYEE].FIRST_NAME,
dbo.[EMPLOYEE].LAST_NAME
